title: 老J的博客
author: 为而不争
email: qustwwy@163.com
description: 专注云原生领域, 包括容器, 微服务, Service Mesh, Serverless等技术, 热衷于参与开源软件和开源社区.
github_username:  llaoj

# url: "https://llaoj.cn"
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

google_analytics: G-K8M9VVHSEF
# disqus:
#   shortname: llaojcn
comment_gitalk_clientId: 3d8481376436f1f1a30d
comment_gitalk_clientSecret: 42796ff9d812cf5242dacc8b07892d35fe1691eb
comment_gitalk_repo: llaoj.github.io
github_username: llaoj