title: 老J的博客
author: 为而不争
email: qustwwy@163.com
description: 专注云原生领域, 包括容器, 微服务, Service Mesh, Serverless等技术, 热衷于参与开源软件和开源社区.
github_username:  llaoj

# url: "https://llaoj.cn"
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

google_analytics: G-K8M9VVHSEF
# disqus:
#   shortname: llaojcn
comment_gitalk_clientId: "Iv1.6444cda2c0d7e66a"
comment_gitalk_clientSecret: "16dd53c6186a48072b4af64d45550faa58e20756"
comment_gitalk_repo: comment.llaoj.github.io
github_username: llaoj